### ISSUE TITLE
Key Events & Dates

### ISSUE THREAD

**Issue by kiphale** [theNewDynamic/aba-icc#107]
1.  The events are not consistent with the timeline and the events appear in an irregular chronological order.

**Comment by budparr** [comment]
what page?

**Comment by kiphale** [comment]
On any case / accused page. EX: Expand key events and look at dates and order of events. All over the place.  https://www.aba-icc.org/cases/case/the-prosecutor-v-bemba/

**Comment by budparr** [comment]
Thanks. I'll check it out. That's something I just fixed last week. 

p.s. didn't mean exactly what page is it happening, but what page would serve as an example, so we can make sure we're "on the same page" :)

**Comment by kiphale** [comment]
Boom! Same page!!! :)
