### ISSUE TITLE
Case Status

### ISSUE THREAD

**Issue by kiphale** [theNewDynamic/aba-icc#109]
1.  The case status on the website does not reflect the changes made on the CMS. Please check the Ruto and Sang case for an illustration.

**Comment by budparr** [comment]
I think it's just not updated in the right place. When I made the platform move I tried to simplify the way we handled cases/events/charges, etc. (seemed people were having a hard time with them) but I fear I didn't quite get it down.

**Comment by budparr** [comment]
what is the correct case status?

**Comment by kiphale** [comment]
Case dismissed or whatever that status is called.

**Comment by budparr** [comment]
Yeah, I see that I have "Charges Status" and "Case Status" as two different things. I should remove "Charges Status" in favor of "Case Status" and display that higher up.

**Comment by kiphale** [comment]
Umm let me look at that on a desktop and let you know. Might be simpler than that.

Sent from my iPhone

On Apr 6, 2016, at 3:56 PM, Bud Parr <notifications@github.com<mailto:notifications@github.com>> wrote:


Yeah, I see that I have "Charges Status" and "Case Status" as two different things. I should remove "Charges Status" in favor of "Case Status" and display that higher up.

**Comment by kiphale** [comment]
Ok well the whole website looks different now, so I gather you are doing some work on it (e.g. case status is entirely gone).

**Comment by budparr** [comment]
The "whole website" - can you send a screenshot?

**Comment by budparr** [comment]
I've limited case status to one location, see screenshot.
<img width="562" alt="screen shot 2016-04-08 at 2 06 35 pm" src="https://cloud.githubusercontent.com/assets/115347/14393138/3e0d7594-fd93-11e5-93f5-6e320454e5bd.png">

**Comment by kiphale** [comment]
![image](https://cloud.githubusercontent.com/assets/8195536/14393239/c45b0332-fd93-11e5-8641-fbff2f163e13.png)

The key events layout and ordering looks different from even yesterday.

**Comment by kiphale** [comment]
Re: case status, that may not be a good idea. With joint accused cases, a case may have different outcomes for different people. For instance, in Prosecutor vs. Bud and Kip, charges could be thrown out against me, but charges against you go forward.

**Comment by budparr** [comment]
I'm working on simplifying the whole thing (and that date issue).

**Comment by budparr** [comment]
I just thought when you said the whole site, something went haywire. We developers like specific language 😄

**Comment by kiphale** [comment]
Ok! Sounds good. Btw, I got off in my example because I know better lawyers, although you could probably pay more, so maybe you would get off. ;)
