### ISSUE TITLE
Central African Republic

### ISSUE THREAD

**Issue by kiphale** [theNewDynamic/aba-icc#111]
The country/situation overview is misleading. 

https://www.aba-icc.org/country/central-african-republic/ 

It should clearly delineate Situation I from Situation II - currently there is no "Situation 1"

The cases listed at the bottom and top are from Situation I, as there are no Situation II cases yet. Defer to you how this may be resolved best.

**Comment by budparr** [comment]
In the first part of this, it's just some copy. Can change that. I can probably separate them though.

**Comment by kiphale** [comment]
I can change that are you saying?

**Comment by budparr** [comment]
don't worry about it. I'll change it, because I need to look at the whole.
